- job:
    name: test-flask-app
    run: playbooks/test-flask-app.yaml
    provides: test-result

- job:
    name: create-docker-container
    run: playbooks/create-container.yaml
    requires: test-result
    nodeset:
      nodes:
        - name: pod-dind
          label: pod-dind

- project:
    check:
      jobs:
        - create-docker-container
    gate:
      jobs:
        - create-docker-container