- job:
    name: test-flask-app
    run: playbooks/test-flask-app.yaml

- job:
    name: create-docker-container
    run: playbooks/setup-container.yaml
    nodeset:
      nodes:
        - name: pod-dind
          label: pod-dind

- project:
    check:
      jobs:
        - create-docker-container
    gate:
      jobs:
        - create-docker-container