- name: Copy Flask app files
  copy:
    src: "../../../{{ item }}"
    dest: "/tmp/flask-app/"
  loop:
    - app.py
    - Dockerfile
    - requirements.txt

- name: Build Docker image
  args:
    chdir: /tmp/flask-app
  shell: docker build -t {{ image.repository }}:{{ image.tag }} .

- name: Run Flask app container
  shell: docker run -p 5000:5000 --name flask-test-container -d {{ image.repository }}:{{ image.tag }} 

- name: Wait for the application to be ready
  wait_for:
    port: 5000
    delay: 10
    timeout: 40

- name: Test Flask app
  uri:
    url: http://localhost:5000
    return_content: yes
  register: flask_response
  failed_when: flask_response.status != 200

- name: Display Flask app response
  debug:
    var: flask_response.content