---
- name: Update apt package index
  become: true
  apt:
    update_cache: yes

- name: Install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker's official GPG key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Set up the stable repository
  become: true
  shell: echo "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt package index after adding Docker repository
  become: true
  apt:
    update_cache: yes

- name: Install Docker Engine
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is running
  become: true
  service:
    name: docker
    state: started
    enabled: yes
  register: docker

- name: Set permission docker
  become: true 
  become_user: root
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: '0666'